In [1]:
# Dependencies
import numpy as np
import pandas as pd

In [1052]:
teams = ["ANA","ARI","ATL","BAL","BOS","CHC","CHW","CIN","CLE","COL","DET",
        "FLA","HOU","KCR","LAD","MIL","MIN","NYM","NYY","OAK","PHI","PIT",
        "SDP","SEA","SFG","STL","TBD","TEX","TOR","WSN"]

In [2]:
draft_full = {}

In [36]:
draft_full["SEA"] = pd.read_csv(f"Resources/complete_SEA_drafts_no_dup.csv")

In [119]:
frames_train = [draft_full["ANA"][0:2014],draft_full["ARI"][0:939],draft_full["ATL"][0:2167],draft_full["BAL"][0:2128],
                draft_full["BOS"][0:1800],draft_full["CHC"][0:2095],draft_full["CHW"][0:2026],draft_full["CIN"][0:2124],
                draft_full["CLE"][0:2226],draft_full["COL"][0:1103],draft_full["DET"][0:2084],draft_full["FLA"][0:1220],
                draft_full["HOU"][0:2198],draft_full["KCR"][0:2148],draft_full["LAD"][0:2312],draft_full["MIL"][0:1895],
                draft_full["MIN"][0:2201],draft_full["NYM"][0:2273],draft_full["NYY"][0:2356],draft_full["OAK"][0:1973],
                draft_full["PHI"][0:2022],draft_full["PIT"][0:2198],draft_full["SDP"][0:1787],draft_full["SEA"][0:1757],
                draft_full["SFG"][0:2154],draft_full["STL"][0:2228],draft_full["TBD"][0:985],draft_full["TEX"][0:2177],
                draft_full["TOR"][0:1728],draft_full["WSN"][0:2011]]

frames_test = [draft_full["ANA"][2015:2174],draft_full["ARI"][940:1099],draft_full["ATL"][2168:2326],draft_full["BAL"][2129:2288],
               draft_full["BOS"][1801:1956],draft_full["CHC"][2096:2252],draft_full["CHW"][2027:2184],draft_full["CIN"][2125:2282],
               draft_full["CLE"][2227:2384],draft_full["COL"][1104:1265],draft_full["DET"][2085:2236],draft_full["FLA"][1221:1378],
               draft_full["HOU"][2199:2361],draft_full["KCR"][2149:2306],draft_full["LAD"][2313:2473],draft_full["MIL"][1896:2055],
               draft_full["MIN"][2202:2362],draft_full["NYM"][2274:2430],draft_full["NYY"][2357:2515],draft_full["OAK"][1974:2129],
               draft_full["PHI"][2023:2177],draft_full["PIT"][2199:2360],draft_full["SDP"][1788:1950],draft_full["SEA"][1758:1916],
               draft_full["SFG"][2155:2309],draft_full["STL"][2229:2389],draft_full["TBD"][986:1148],draft_full["TEX"][2178:2335],
               draft_full["TOR"][1729:1889],draft_full["WSN"][2012:2168]]

full_train_df = pd.concat(frames_train)

full_test_df = pd.concat(frames_test)
output_df = pd.concat(frames_test)

In [125]:
full_train_df.to_csv("Resources/draft_1965_2014.csv")
full_test_df.to_csv("Resources/draft_2015_2018.csv")

In [45]:
full_test_df.head()

,AB,BA,Column1,ERA,GPi,GPl,Gpi,HR,L,Name,...,SV,Signed,Tm,Type,W,WAR,WHIP,Year,school,town
2015,0,0.0,2780,0.0,NaN,0,0.0,0,0,Taylor Ward (minors),...,0,Y,Angels,4Yr,0,0.0,0.0,2015,California State University Fresno,Fresno
2016,0,0.0,2781,0.0,NaN,0,0.0,0,0,Jahmai Jones (minors),...,0,Y,Angels,HS,0,0.0,0.0,2015,Wesleyan School,Norcross
2017,0,0.0,2782,0.0,NaN,0,0.0,0,0,Grayson Long (minors),...,0,Y,Angels,4Yr,0,0.0,0.0,2015,Texas A&M University,College Station
2018,0,0.0,2783,0.0,NaN,0,0.0,0,0,Brendon Sanger (minors),...,0,Y,Angels,4Yr,0,0.0,0.0,2015,Florida Atlantic University,Boca Raton
2019,0,0.0,2784,0.0,NaN,0,0.0,0,0,Jared Foster (minors),...,0,Y,Angels,4Yr,0,0.0,0.0,2015,Louisiana State University,Baton Rouge

In [92]:
del full_train_df["Column1"]
del full_train_df["Year"]
del full_train_df["Rnd"]
del full_train_df["RdPck"]
del full_train_df["Tm"]
del full_train_df["Name"]
del full_train_df["GPl"]
del full_train_df["AB"]
del full_train_df["HR"]
del full_train_df["BA"]
del full_train_df["OPS"]
del full_train_df["GPi"]
del full_train_df["Gpi"]
del full_train_df["W"]
del full_train_df["L"]
del full_train_df["ERA"]
del full_train_df["WHIP"]
del full_train_df["SV"]
del full_train_df["school"]
del full_train_df["town"]
del full_train_df["Signed"]
full_train_df.head()

   OvPck  Pos  ST Type  WAR
0     11   1B  MD   HS  2.8
1     31  RHP  CA   HS  0.7
2     51  RHP  CA   HS  0.1
3     67    C  WA  4Yr  0.0
4     87   3B  CA   HS -0.8

In [93]:
del full_test_df["Column1"]
del full_test_df["Year"]
del full_test_df["Rnd"]
del full_test_df["RdPck"]
del full_test_df["Tm"]
del full_test_df["Name"]
del full_test_df["GPl"]
del full_test_df["AB"]
del full_test_df["HR"]
del full_test_df["BA"]
del full_test_df["OPS"]
del full_test_df["GPi"]
del full_test_df["Gpi"]
del full_test_df["W"]
del full_test_df["L"]
del full_test_df["ERA"]
del full_test_df["WHIP"]
del full_test_df["SV"]
del full_test_df["school"]
del full_test_df["town"]
del full_test_df["Signed"]
full_test_df.head()

      OvPck  Pos  ST Type  WAR
2015     26    C  CA  4Yr  0.0
2016     70   OF  GA   HS  0.0
2017    104  RHP  TX  4Yr  0.0
2018    135   RF  FL  4Yr  0.0
2019    165   RF  LA  4Yr  0.0

In [94]:
full_test_df = full_test_df.reset_index(drop=True)
full_test_df.head()

   OvPck  Pos  ST Type  WAR
0     26    C  CA  4Yr  0.0
1     70   OF  GA   HS  0.0
2    104  RHP  TX  4Yr  0.0
3    135   RF  FL  4Yr  0.0
4    165   RF  LA  4Yr  0.0

In [95]:
train_value = []
for row in full_train_df["WAR"]:
    if row > 70:
        train_value.append(">70 WAR")
    elif row > 40:
        train_value.append("40<WAR<70")
    elif row > 20:
        train_value.append("20<AR<40")
    elif row > 10:
        train_value.append("10<WAR<20")
    elif row > 5:
        train_value.append("5<WAR<10")
    elif row > 0:
        train_value.append("0<WAR<5")
    elif row == 0:
        train_value.append("NO WAR")
    elif row < 0:
        train_value.append("<0 WAR")

In [96]:
data = {"WAR": train_value}
train_WAR_df = pd.DataFrame(data)
train_WAR_df.head()

       WAR
0  0<WAR<5
1  0<WAR<5
2  0<WAR<5
3   NO WAR
4   <0 WAR

In [97]:
del full_train_df["WAR"]
del full_test_df["WAR"]
train_data_binary_encoded = pd.get_dummies(full_train_df)
test_data_binary_encoded = pd.get_dummies(full_test_df)

In [98]:
output_value = len(train_WAR_df.WAR.unique())

In [99]:
X_train = train_data_binary_encoded
y_train = train_WAR_df
X_test = test_data_binary_encoded
print("Train shape: ", X_train.shape, y_train.shape)
print("Test shape: ", X_test.shape)

Train shape:  (58329, 98) (58329, 1)
Test shape:  (4737, 78)

In [100]:
X_train.to_csv("Resources/X_train_1.csv")
X_test.to_csv("Resources/X_test_1.csv")

In [101]:
X_train = pd.read_csv("Resources/X_train_1.csv")
X_test = pd.read_csv("Resources/X_test_1.csv")

In [102]:
print("Train shape: ", X_train.shape, y_train.shape)
print("Test shape: ", X_test.shape)

Train shape:  (58329, 87) (58329, 1)
Test shape:  (4737, 87)

In [103]:
from keras.models import Sequential
from keras.layers import Dense

# Create model and add layers
def build_classifier():
    classifier = Sequential()
    classifier.add(Dense(units=100, activation='relu', input_dim=87))
    classifier.add(Dense(units=100, activation='relu'))
    classifier.add(Dense(units=output_value, activation='softmax'))
    classifier.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])
    return classifier

# Create a Keras model that's compatible with scikit-learn
from keras.callbacks import EarlyStopping
from keras.wrappers.scikit_learn import KerasClassifier
keras_classifier = KerasClassifier(build_classifier, epochs=300, shuffle=True, verbose=2, callbacks=[EarlyStopping(monitor='acc', patience=20, verbose=2)])

In [104]:
from sklearn.preprocessing import LabelEncoder
from keras.utils import to_categorical

# Step 1: Label-encode data set
label_encoder = LabelEncoder()
label_encoder.fit(y_train)
encoded_y_train = label_encoder.transform(y_train)

# Step 2: Convert encoded labels to one-hot-encoding
y_train_categorical = to_categorical(encoded_y_train)

C:\Users\mattm\Anaconda3\envs\PythonData\lib\site-packages\sklearn\preprocessing\label.py:95: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\mattm\Anaconda3\envs\PythonData\lib\site-packages\sklearn\preprocessing\label.py:128: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

In [114]:
# Ensure we are scaling features
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import make_pipeline
model = make_pipeline(StandardScaler(), keras_classifier)

In [115]:
model.fit(X_train, y_train_categorical)

Epoch 1/300
 - 2s - loss: 0.5735 - acc: 0.8615
Epoch 2/300
 - 2s - loss: 0.5397 - acc: 0.8653
Epoch 3/300
 - 2s - loss: 0.5328 - acc: 0.8653
Epoch 4/300
 - 2s - loss: 0.5280 - acc: 0.8654
Epoch 5/300
 - 2s - loss: 0.5251 - acc: 0.8652
Epoch 6/300
 - 2s - loss: 0.5222 - acc: 0.8655
Epoch 7/300
 - 2s - loss: 0.5196 - acc: 0.8658
Epoch 8/300
 - 2s - loss: 0.5166 - acc: 0.8657
Epoch 9/300
 - 2s - loss: 0.5147 - acc: 0.8656
Epoch 10/300
 - 2s - loss: 0.5120 - acc: 0.8660
Epoch 11/300
 - 2s - loss: 0.5095 - acc: 0.8656
Epoch 12/300
 - 2s - loss: 0.5075 - acc: 0.8658
Epoch 13/300
 - 2s - loss: 0.5042 - acc: 0.8663
Epoch 14/300
 - 2s - loss: 0.5014 - acc: 0.8660
Epoch 15/300
 - 2s - loss: 0.5004 - acc: 0.8666
Epoch 16/300
 - 2s - loss: 0.4973 - acc: 0.8663
Epoch 17/300
 - 2s - loss: 0.4953 - acc: 0.8667
Epoch 18/300
 - 2s - loss: 0.4932 - acc: 0.8667
Epoch 19/300
 - 2s - loss: 0.4907 - acc: 0.8673
Epoch 20/300
 - 2s - loss: 0.4893 - acc: 0.8670
Epoch 21/300
 - 2s - loss: 0.4872 - acc: 0.8669
Epoch 22/300
 - 2s - loss: 0.4860 - acc: 0.8670
Epoch 23/300
 - 2s - loss: 0.4845 - acc: 0.8671
Epoch 24/300
 - 2s - loss: 0.4817 - acc: 0.8674
Epoch 25/300
 - 2s - loss: 0.4801 - acc: 0.8666
Epoch 26/300
 - 2s - loss: 0.4785 - acc: 0.8675
Epoch 27/300
 - 2s - loss: 0.4770 - acc: 0.8676
Epoch 28/300
 - 2s - loss: 0.4749 - acc: 0.8673
Epoch 29/300
 - 2s - loss: 0.4735 - acc: 0.8681
Epoch 30/300
 - 2s - loss: 0.4721 - acc: 0.8681
Epoch 31/300
 - 2s - loss: 0.4709 - acc: 0.8687
Epoch 32/300
 - 2s - loss: 0.4694 - acc: 0.8680
Epoch 33/300
 - 2s - loss: 0.4683 - acc: 0.8679
Epoch 34/300
 - 2s - loss: 0.4659 - acc: 0.8682
Epoch 35/300
 - 2s - loss: 0.4650 - acc: 0.8685
Epoch 36/300
 - 2s - loss: 0.4644 - acc: 0.8684
Epoch 37/300
 - 2s - loss: 0.4624 - acc: 0.8683
Epoch 38/300
 - 2s - loss: 0.4616 - acc: 0.8684
Epoch 39/300
 - 2s - loss: 0.4600 - acc: 0.8688
Epoch 40/300
 - 2s - loss: 0.4581 - acc: 0.8690
Epoch 41/300
 - 2s - loss: 0.4570 - acc: 0.8698
Epoch 42/300
 - 2s - loss: 0.4570 - acc: 0.8687
Epoch 43/300
 - 2s - loss: 0.4564 - acc: 0.8691
Epoch 44/300
 - 2s - loss: 0.4544 - acc: 0.8692
Epoch 45/300
 - 2s - loss: 0.4532 - acc: 0.8696
Epoch 46/300
 - 2s - loss: 0.4520 - acc: 0.8694
Epoch 47/300
 - 2s - loss: 0.4505 - acc: 0.8698
Epoch 48/300
 - 2s - loss: 0.4508 - acc: 0.8696
Epoch 49/300
 - 2s - loss: 0.4489 - acc: 0.8695
Epoch 50/300
 - 2s - loss: 0.4484 - acc: 0.8703
Epoch 51/300
 - 2s - loss: 0.4470 - acc: 0.8700
Epoch 52/300
 - 2s - loss: 0.4470 - acc: 0.8695
Epoch 53/300
 - 2s - loss: 0.4452 - acc: 0.8702
Epoch 54/300
 - 2s - loss: 0.4447 - acc: 0.8708
Epoch 55/300
 - 2s - loss: 0.4440 - acc: 0.8706
Epoch 56/300
 - 2s - loss: 0.4422 - acc: 0.8703
Epoch 57/300
 - 2s - loss: 0.4425 - acc: 0.8696
Epoch 58/300
 - 2s - loss: 0.4414 - acc: 0.8703
Epoch 59/300
 - 2s - loss: 0.4409 - acc: 0.8702
Epoch 60/300
 - 2s - loss: 0.4400 - acc: 0.8711
Epoch 61/300
 - 2s - loss: 0.4397 - acc: 0.8704
Epoch 62/300
 - 2s - loss: 0.4381 - acc: 0.8711
Epoch 63/300
 - 2s - loss: 0.4379 - acc: 0.8707
Epoch 64/300
 - 2s - loss: 0.4366 - acc: 0.8710
Epoch 65/300
 - 2s - loss: 0.4373 - acc: 0.8709
Epoch 66/300
 - 2s - loss: 0.4357 - acc: 0.8710
Epoch 67/300
 - 2s - loss: 0.4349 - acc: 0.8711
Epoch 68/300
 - 2s - loss: 0.4345 - acc: 0.8711
Epoch 69/300
 - 2s - loss: 0.4345 - acc: 0.8709
Epoch 70/300
 - 2s - loss: 0.4330 - acc: 0.8713
Epoch 71/300
 - 2s - loss: 0.4319 - acc: 0.8711
Epoch 72/300
 - 2s - loss: 0.4316 - acc: 0.8715
Epoch 73/300
 - 2s - loss: 0.4314 - acc: 0.8714
Epoch 74/300
 - 2s - loss: 0.4312 - acc: 0.8716
Epoch 75/300
 - 2s - loss: 0.4293 - acc: 0.8717
Epoch 76/300
 - 2s - loss: 0.4292 - acc: 0.8714
Epoch 77/300
 - 2s - loss: 0.4290 - acc: 0.8717
Epoch 78/300
 - 2s - loss: 0.4278 - acc: 0.8718
Epoch 79/300
 - 2s - loss: 0.4281 - acc: 0.8717
Epoch 80/300
 - 2s - loss: 0.4269 - acc: 0.8721
Epoch 81/300
 - 2s - loss: 0.4263 - acc: 0.8720
Epoch 82/300
 - 2s - loss: 0.4263 - acc: 0.8721
Epoch 83/300
 - 2s - loss: 0.4253 - acc: 0.8717
Epoch 84/300
 - 2s - loss: 0.4258 - acc: 0.8723
Epoch 85/300
 - 2s - loss: 0.4241 - acc: 0.8724
Epoch 86/300
 - 2s - loss: 0.4235 - acc: 0.8724
Epoch 87/300
 - 2s - loss: 0.4257 - acc: 0.8723
Epoch 88/300
 - 2s - loss: 0.4257 - acc: 0.8720
Epoch 89/300
 - 2s - loss: 0.4245 - acc: 0.8725
Epoch 90/300
 - 2s - loss: 0.4236 - acc: 0.8726
Epoch 91/300
 - 2s - loss: 0.4218 - acc: 0.8726
Epoch 92/300
 - 2s - loss: 0.4203 - acc: 0.8727
Epoch 93/300
 - 2s - loss: 0.4213 - acc: 0.8721
Epoch 94/300
 - 2s - loss: 0.4187 - acc: 0.8727
Epoch 95/300
 - 2s - loss: 0.4205 - acc: 0.8731
Epoch 96/300
 - 2s - loss: 0.4199 - acc: 0.8736
Epoch 97/300
 - 2s - loss: 0.4190 - acc: 0.8729
Epoch 98/300
 - 2s - loss: 0.4186 - acc: 0.8730
Epoch 99/300
 - 2s - loss: 0.4171 - acc: 0.8726
Epoch 100/300
 - 2s - loss: 0.4185 - acc: 0.8727
Epoch 101/300
 - 2s - loss: 0.4179 - acc: 0.8731
Epoch 102/300
 - 2s - loss: 0.4163 - acc: 0.8732
Epoch 103/300
 - 2s - loss: 0.4173 - acc: 0.8735
Epoch 104/300
 - 2s - loss: 0.4161 - acc: 0.8729
Epoch 105/300
 - 2s - loss: 0.4152 - acc: 0.8737
Epoch 106/300
 - 2s - loss: 0.4157 - acc: 0.8728
Epoch 107/300
 - 2s - loss: 0.4135 - acc: 0.8729
Epoch 108/300
 - 2s - loss: 0.4146 - acc: 0.8735
Epoch 109/300
 - 2s - loss: 0.4138 - acc: 0.8736
Epoch 110/300
 - 2s - loss: 0.4127 - acc: 0.8736
Epoch 111/300
 - 2s - loss: 0.4129 - acc: 0.8739
Epoch 112/300
 - 2s - loss: 0.4138 - acc: 0.8734
Epoch 113/300
 - 2s - loss: 0.4147 - acc: 0.8735
Epoch 114/300
 - 2s - loss: 0.4151 - acc: 0.8736
Epoch 115/300
 - 2s - loss: 0.4135 - acc: 0.8739
Epoch 116/300
 - 2s - loss: 0.4140 - acc: 0.8741
Epoch 117/300
 - 2s - loss: 0.4126 - acc: 0.8738
Epoch 118/300
 - 2s - loss: 0.4112 - acc: 0.8736
Epoch 119/300
 - 3s - loss: 0.4097 - acc: 0.8738
Epoch 120/300
 - 2s - loss: 0.4100 - acc: 0.8736
Epoch 121/300
 - 2s - loss: 0.4092 - acc: 0.8736
Epoch 122/300
 - 2s - loss: 0.4091 - acc: 0.8743
Epoch 123/300
 - 2s - loss: 0.4087 - acc: 0.8744
Epoch 124/300
 - 2s - loss: 0.4084 - acc: 0.8742
Epoch 125/300
 - 2s - loss: 0.4083 - acc: 0.8742
Epoch 126/300
 - 2s - loss: 0.4080 - acc: 0.8741
Epoch 127/300
 - 2s - loss: 0.4059 - acc: 0.8744
Epoch 128/300
 - 2s - loss: 0.4080 - acc: 0.8748
Epoch 129/300
 - 2s - loss: 0.4063 - acc: 0.8738
Epoch 130/300
 - 2s - loss: 0.4073 - acc: 0.8742
Epoch 131/300
 - 2s - loss: 0.4043 - acc: 0.8744
Epoch 132/300
 - 2s - loss: 0.4058 - acc: 0.8744
Epoch 133/300
 - 3s - loss: 0.4045 - acc: 0.8750
Epoch 134/300
 - 2s - loss: 0.4051 - acc: 0.8750
Epoch 135/300
 - 2s - loss: 0.4040 - acc: 0.8754
Epoch 136/300
 - 2s - loss: 0.4050 - acc: 0.8745
Epoch 137/300
 - 2s - loss: 0.4041 - acc: 0.8751
Epoch 138/300
 - 2s - loss: 0.4040 - acc: 0.8748
Epoch 139/300
 - 2s - loss: 0.4037 - acc: 0.8753
Epoch 140/300
 - 2s - loss: 0.4033 - acc: 0.8752
Epoch 141/300
 - 2s - loss: 0.4021 - acc: 0.8744
Epoch 142/300
 - 2s - loss: 0.4036 - acc: 0.8751
Epoch 143/300
 - 2s - loss: 0.4011 - acc: 0.8754
Epoch 144/300
 - 2s - loss: 0.4027 - acc: 0.8746
Epoch 145/300
 - 2s - loss: 0.4008 - acc: 0.8747
Epoch 146/300
 - 2s - loss: 0.4012 - acc: 0.8751
Epoch 147/300
 - 2s - loss: 0.4011 - acc: 0.8752
Epoch 148/300
 - 2s - loss: 0.4003 - acc: 0.8760
Epoch 149/300
 - 2s - loss: 0.4017 - acc: 0.8756
Epoch 150/300
 - 3s - loss: 0.4006 - acc: 0.8757
Epoch 151/300
 - 3s - loss: 0.3987 - acc: 0.8759
Epoch 152/300
 - 2s - loss: 0.3995 - acc: 0.8757
Epoch 153/300
 - 3s - loss: 0.3991 - acc: 0.8758
Epoch 154/300
 - 3s - loss: 0.3984 - acc: 0.8756
Epoch 155/300
 - 2s - loss: 0.3992 - acc: 0.8754
Epoch 156/300
 - 2s - loss: 0.3993 - acc: 0.8757
Epoch 157/300
 - 2s - loss: 0.3993 - acc: 0.8760
Epoch 158/300
 - 3s - loss: 0.3972 - acc: 0.8748
Epoch 159/300
 - 2s - loss: 0.3983 - acc: 0.8752
Epoch 160/300
 - 2s - loss: 0.3985 - acc: 0.8758
Epoch 161/300
 - 2s - loss: 0.3983 - acc: 0.8754
Epoch 162/300
 - 2s - loss: 0.3969 - acc: 0.8762
Epoch 163/300
 - 2s - loss: 0.3972 - acc: 0.8766
Epoch 164/300
 - 2s - loss: 0.3987 - acc: 0.8752
Epoch 165/300
 - 2s - loss: 0.3969 - acc: 0.8758
Epoch 166/300
 - 2s - loss: 0.3988 - acc: 0.8754
Epoch 167/300
 - 2s - loss: 0.3957 - acc: 0.8762
Epoch 168/300
 - 2s - loss: 0.3961 - acc: 0.8756
Epoch 169/300
 - 2s - loss: 0.3965 - acc: 0.8758
Epoch 170/300
 - 2s - loss: 0.3947 - acc: 0.8771

Epoch 171/300
 - 2s - loss: 0.3964 - acc: 0.8762
Epoch 172/300
 - 3s - loss: 0.3955 - acc: 0.8761
Epoch 173/300
 - 2s - loss: 0.3952 - acc: 0.8762
Epoch 174/300
 - 2s - loss: 0.3948 - acc: 0.8767
Epoch 175/300
 - 2s - loss: 0.3948 - acc: 0.8765
Epoch 176/300
 - 2s - loss: 0.3979 - acc: 0.8760
Epoch 177/300
 - 2s - loss: 0.3926 - acc: 0.8760
Epoch 178/300
 - 2s - loss: 0.3940 - acc: 0.8765
Epoch 179/300
 - 2s - loss: 0.3946 - acc: 0.8763
Epoch 180/300
 - 2s - loss: 0.3926 - acc: 0.8771
Epoch 181/300
 - 2s - loss: 0.3935 - acc: 0.8770
Epoch 182/300
 - 2s - loss: 0.3940 - acc: 0.8765
Epoch 183/300
 - 2s - loss: 0.3914 - acc: 0.8769
Epoch 184/300
 - 2s - loss: 0.3931 - acc: 0.8765
Epoch 185/300
 - 2s - loss: 0.3926 - acc: 0.8765
Epoch 186/300
 - 2s - loss: 0.3918 - acc: 0.8759
Epoch 187/300
 - 2s - loss: 0.3907 - acc: 0.8776
Epoch 188/300
 - 2s - loss: 0.3922 - acc: 0.8767
Epoch 189/300
 - 2s - loss: 0.3909 - acc: 0.8770
Epoch 190/300
 - 2s - loss: 0.3898 - acc: 0.8769
Epoch 191/300
 - 2s - loss: 0.3917 - acc: 0.8766
Epoch 192/300
 - 2s - loss: 0.3906 - acc: 0.8769
Epoch 193/300
 - 2s - loss: 0.3905 - acc: 0.8771
Epoch 194/300
 - 2s - loss: 0.3909 - acc: 0.8763
Epoch 195/300
 - 2s - loss: 0.3905 - acc: 0.8765
Epoch 196/300
 - 2s - loss: 0.3888 - acc: 0.8770
Epoch 197/300
 - 2s - loss: 0.3893 - acc: 0.8770
Epoch 198/300
 - 2s - loss: 0.3877 - acc: 0.8773
Epoch 199/300
 - 2s - loss: 0.3899 - acc: 0.8771
Epoch 200/300
 - 2s - loss: 0.3900 - acc: 0.8777
Epoch 201/300
 - 2s - loss: 0.3879 - acc: 0.8768
Epoch 202/300
 - 2s - loss: 0.3881 - acc: 0.8775
Epoch 203/300
 - 2s - loss: 0.3884 - acc: 0.8769
Epoch 204/300
 - 2s - loss: 0.3884 - acc: 0.8767
Epoch 205/300
 - 2s - loss: 0.3870 - acc: 0.8773
Epoch 206/300
 - 2s - loss: 0.3869 - acc: 0.8770
Epoch 207/300
 - 2s - loss: 0.3864 - acc: 0.8781
Epoch 208/300
 - 2s - loss: 0.3877 - acc: 0.8768
Epoch 209/300
 - 2s - loss: 0.3863 - acc: 0.8777
Epoch 210/300
 - 2s - loss: 0.3869 - acc: 0.8777
Epoch 211/300
 - 2s - loss: 0.3871 - acc: 0.8773
Epoch 212/300
 - 2s - loss: 0.3849 - acc: 0.8776
Epoch 213/300
 - 2s - loss: 0.3861 - acc: 0.8775
Epoch 214/300
 - 2s - loss: 0.3858 - acc: 0.8772
Epoch 215/300
 - 2s - loss: 0.3862 - acc: 0.8778
Epoch 216/300
 - 2s - loss: 0.3852 - acc: 0.8779
Epoch 217/300
 - 2s - loss: 0.3853 - acc: 0.8784
Epoch 218/300
 - 2s - loss: 0.3857 - acc: 0.8773
Epoch 219/300
 - 2s - loss: 0.3855 - acc: 0.8777
Epoch 220/300
 - 2s - loss: 0.3859 - acc: 0.8777
Epoch 221/300
 - 2s - loss: 0.3840 - acc: 0.8779
Epoch 222/300
 - 2s - loss: 0.3848 - acc: 0.8776
Epoch 223/300
 - 2s - loss: 0.3858 - acc: 0.8771
Epoch 224/300
 - 2s - loss: 0.3847 - acc: 0.8786
Epoch 225/300
 - 2s - loss: 0.3861 - acc: 0.8778
Epoch 226/300
 - 2s - loss: 0.3829 - acc: 0.8783
Epoch 227/300
 - 2s - loss: 0.3832 - acc: 0.8781
Epoch 228/300
 - 2s - loss: 0.3831 - acc: 0.8781
Epoch 229/300
 - 2s - loss: 0.3826 - acc: 0.8787
Epoch 230/300
 - 2s - loss: 0.3823 - acc: 0.8780
Epoch 231/300
 - 2s - loss: 0.3838 - acc: 0.8782
Epoch 232/300
 - 2s - loss: 0.3834 - acc: 0.8778
Epoch 233/300
 - 2s - loss: 0.3845 - acc: 0.8777
Epoch 234/300
 - 2s - loss: 0.3827 - acc: 0.8780
Epoch 235/300
 - 2s - loss: 0.3836 - acc: 0.8781
Epoch 236/300
 - 2s - loss: 0.3833 - acc: 0.8778
Epoch 237/300
 - 2s - loss: 0.3825 - acc: 0.8784
Epoch 238/300
 - 2s - loss: 0.3824 - acc: 0.8785
Epoch 239/300
 - 2s - loss: 0.3811 - acc: 0.8790
Epoch 240/300
 - 2s - loss: 0.3816 - acc: 0.8779
Epoch 241/300
 - 2s - loss: 0.3801 - acc: 0.8788
Epoch 242/300
 - 2s - loss: 0.3800 - acc: 0.8786
Epoch 243/300
 - 2s - loss: 0.3819 - acc: 0.8785
Epoch 244/300
 - 2s - loss: 0.3814 - acc: 0.8787
Epoch 245/300
 - 2s - loss: 0.3810 - acc: 0.8789
Epoch 246/300
 - 2s - loss: 0.3795 - acc: 0.8793
Epoch 247/300
 - 2s - loss: 0.3810 - acc: 0.8783
Epoch 248/300
 - 2s - loss: 0.3812 - acc: 0.8789
Epoch 249/300
 - 2s - loss: 0.3794 - acc: 0.8787
Epoch 250/300
 - 2s - loss: 0.3783 - acc: 0.8795
Epoch 251/300
 - 2s - loss: 0.3774 - acc: 0.8787
Epoch 252/300
 - 2s - loss: 0.3786 - acc: 0.8791
Epoch 253/300
 - 2s - loss: 0.3789 - acc: 0.8792
Epoch 254/300
 - 2s - loss: 0.3789 - acc: 0.8788
Epoch 255/300
 - 2s - loss: 0.3784 - acc: 0.8800
Epoch 256/300
 - 2s - loss: 0.3768 - acc: 0.8798
Epoch 257/300
 - 2s - loss: 0.3796 - acc: 0.8790
Epoch 258/300
 - 2s - loss: 0.3780 - acc: 0.8793
Epoch 259/300
 - 2s - loss: 0.3766 - acc: 0.8789
Epoch 260/300
 - 2s - loss: 0.3784 - acc: 0.8799
Epoch 261/300
 - 2s - loss: 0.3775 - acc: 0.8791
Epoch 262/300
 - 2s - loss: 0.3781 - acc: 0.8784
Epoch 263/300
 - 2s - loss: 0.3778 - acc: 0.8788
Epoch 264/300
 - 2s - loss: 0.3771 - acc: 0.8786
Epoch 265/300
 - 2s - loss: 0.3778 - acc: 0.8789
Epoch 266/300
 - 2s - loss: 0.3766 - acc: 0.8788
Epoch 267/300
 - 2s - loss: 0.3771 - acc: 0.8794
Epoch 268/300
 - 2s - loss: 0.3778 - acc: 0.8796
Epoch 269/300
 - 2s - loss: 0.3767 - acc: 0.8801
Epoch 270/300
 - 2s - loss: 0.3764 - acc: 0.8802
Epoch 271/300
 - 2s - loss: 0.3773 - acc: 0.8788
Epoch 272/300
 - 2s - loss: 0.3774 - acc: 0.8790
Epoch 273/300
 - 2s - loss: 0.3753 - acc: 0.8802
Epoch 274/300
 - 2s - loss: 0.3751 - acc: 0.8791
Epoch 275/300
 - 2s - loss: 0.3756 - acc: 0.8803
Epoch 276/300
 - 2s - loss: 0.3759 - acc: 0.8794
Epoch 277/300
 - 2s - loss: 0.3751 - acc: 0.8795
Epoch 278/300
 - 2s - loss: 0.3754 - acc: 0.8794
Epoch 279/300
 - 2s - loss: 0.3759 - acc: 0.8794
Epoch 280/300
 - 2s - loss: 0.3752 - acc: 0.8793
Epoch 281/300
 - 2s - loss: 0.3749 - acc: 0.8799
Epoch 282/300
 - 2s - loss: 0.3730 - acc: 0.8797
Epoch 283/300
 - 2s - loss: 0.3742 - acc: 0.8800
Epoch 284/300
 - 2s - loss: 0.3738 - acc: 0.8795
Epoch 285/300
 - 2s - loss: 0.3736 - acc: 0.8799
Epoch 286/300
 - 2s - loss: 0.3737 - acc: 0.8804
Epoch 287/300
 - 2s - loss: 0.3739 - acc: 0.8792
Epoch 288/300
 - 2s - loss: 0.3728 - acc: 0.8803
Epoch 289/300
 - 3s - loss: 0.3735 - acc: 0.8802
Epoch 290/300
 - 2s - loss: 0.3726 - acc: 0.8801
Epoch 291/300
 - 2s - loss: 0.3724 - acc: 0.8794
Epoch 292/300
 - 2s - loss: 0.3734 - acc: 0.8794
Epoch 293/300
 - 2s - loss: 0.3744 - acc: 0.8797
Epoch 294/300
 - 2s - loss: 0.3733 - acc: 0.8803
Epoch 295/300
 - 2s - loss: 0.3727 - acc: 0.8798
Epoch 296/300
 - 2s - loss: 0.3735 - acc: 0.8792
Epoch 297/300
 - 2s - loss: 0.3727 - acc: 0.8806
Epoch 298/300
 - 2s - loss: 0.3719 - acc: 0.8809
Epoch 299/300
 - 2s - loss: 0.3723 - acc: 0.8795
Epoch 300/300
 - 2s - loss: 0.3722 - acc: 0.8804

Pipeline(memory=None,
     steps=[('standardscaler', StandardScaler(copy=True, with_mean=True, with_std=True)), ('kerasclassifier', <keras.wrappers.scikit_learn.KerasClassifier object at 0x0000016141D95BE0>)])

In [124]:
# Save the model
keras_classifier.model.save("draft_model_trained_ovpck.h5")

In [116]:
encoded_predictions = model.predict(X_test)
encoded_predictions

array([7, 7, 7, ..., 0, 0, 0])

In [117]:
prediction_labels = label_encoder.inverse_transform(encoded_predictions)

C:\Users\mattm\Anaconda3\envs\PythonData\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:

In [120]:
del output_df["Column1"]
del output_df["Year"]
del output_df["RdPck"]
del output_df["GPl"]
del output_df["AB"]
del output_df["HR"]
del output_df["BA"]
del output_df["OPS"]
del output_df["GPi"]
del output_df["Gpi"]
del output_df["W"]
del output_df["L"]
del output_df["ERA"]
del output_df["WHIP"]
del output_df["SV"]
del output_df["school"]
del output_df["town"]
del output_df["Signed"]

In [121]:
output_df["WAR_prediction"] = prediction_labels

In [122]:
output_df.head()

,Name,OvPck,Pos,Rnd,ST,Tm,Type,WAR,WAR_prediction
2015,Taylor Ward (minors),26,C,1,CA,Angels,4Yr,0.0,NO WAR
2016,Jahmai Jones (minors),70,OF,2,GA,Angels,HS,0.0,NO WAR
2017,Grayson Long (minors),104,RHP,3,TX,Angels,4Yr,0.0,NO WAR
2018,Brendon Sanger (minors),135,RF,4,FL,Angels,4Yr,0.0,NO WAR
2019,Jared Foster (minors),165,RF,5,LA,Angels,4Yr,0.0,NO WAR

In [123]:
output_df.to_csv(f"Resources/full_draft_prediction_OvPck.csv")